### ISSUE TITLE
Multi-class classifier?

### ISSUE THREAD

**Issue by chilampoon** [marchion/switchBox#1]
Hi! 
I aim to use the kTSP algorithm to do cancer outcome prediction, the binary part is done, however this package cannot be used to do multiclass prediction. So is there any way to do that? Thanks!

**Comment by marchion** [comment]
There isn't an implementation in the package, but you can do it in two ways:
1) compare each class to the the other ones combined and train a k-TSP (or do all pair-wise comparisons between classes, if there are not too many)
2) count the votes for each pair comparison
3) classify accordingly based on the majority rule

Some cases might not be classifiable.

Luigi

**Comment by chilampoon** [comment]
Got it, thanks!
