### ISSUE TITLE
What kind of unit should be used?

### ISSUE THREAD

**Issue by chilampoon** [marchion/switchBox#2]
I am confused about the units of expression values used in kTSP program or even other ML applications. 

From my point of view, for RNA-seq data, the input values of kTSP must be within-sample normalized, correcting for the gene length, because the algorithm compares the feature values within each sample and no need to do the between-sample comparison. 

However, usually a selection (DE analysis) is prior to tsp score calculation, and the DEA should use values that are within- and between-sample normalized. I think those after __TMM normalization__ and __logCPM transformation__ are feasible for both DEA and kTSP and they are also what limma needs. 

I am not sure about it so I ask for your advice here. Thanks.

**Comment by marchion** [comment]
Dear Chi-Lam,

TSP and kTSP are ranked based, so the results will be the same if the normalization method you apply don't change the ordering of the gens within samples. Definitely using TPM makes sense to obtain a meaningful gene ordering within a sample. I usually also correct for library depth to avoid different samples to be on different scales.

Ultimately, the algorithm will work with ranks in any case, so you should perform any normalization that you think is necessary to obtain meaningful ranks.

Best

Luigi

**Comment by chilampoon** [comment]
Thanks for your reply! Yes, TPM is the suitable one for TSP algorithm. TMM normalization doesn't account for gene length correction as I dig deeper today. And could you please tell me how do you do the library depth correction?

**Comment by chilampoon** [comment]
> Dear Chi-Lam,
> 
> TSP and kTSP are ranked based, so the results will be the same if the normalization method you apply don't change the ordering of the gens within samples. Definitely using TPM makes sense to obtain a meaningful gene ordering within a sample. I usually also correct for library depth to avoid different samples to be on different scales.
> 
> Ultimately, the algorithm will work with ranks in any case, so you should perform any normalization that you think is necessary to obtain meaningful ranks.
> 
> Best
> 
> Luigi

Thanks for your reply! Yes, TPM is the suitable one for TSP algorithm. TMM normalization doesn't account for gene length correction as I dig deeper today. And could you please tell me how do you do the library depth correction?

**Comment by marchion** [comment]
Dear Chi-Lam,

You can learn more here about RNAseq data normalization:

https://ro-che.info/articles/2016-11-28-rna-seq-normalization
